'''
The file for storing linkedin pre-saved stuff
'''

linkedin_job_titles = [
    "Marketing Coordinator",
    "Digital Marketing Specialist",
    "Social Media Manager",
    "Content Strategist",
    "SEO Specialist",
    "Brand Manager",
    "Marketing Analyst",
    "Public Relations Specialist",
    "Advertising Manager",
    "Product Marketing Manager",
    "Finance Manager",
    "Accountant",
    "Financial Analyst",
    "Budget Analyst",
    "Auditor",
    "Tax Advisor",
    "Credit Analyst",
    "Investment Analyst",
    "Risk Manager",
    "Treasury Analyst",
    "Software Engineer",
    "IT Specialist",
    "Network Administrator",
    "Systems Analyst",
    "Data Scientist",
    "Full Stack Developer",
    "Front End Developer",
    "Back End Developer",
    "DevOps Engineer",
    "Cybersecurity Specialist",
    "Database Administrator",
    "Information Systems Architect",
    "Business Analyst",
    "IT Project Manager",
    "Web Designer",
    "SEO Consultant",
    "Sales Representative",
    "Account Executive",
    "Product Manager",
    "Customer Success Manager",
    "Project Coordinator",
    "Project Manager",
    "Operations Manager",
    "Office Manager",
    "Employee Relations Manager",
    "Community Manager"
]

linkedin_skills = [
    "Communication",
    "Teamwork",
    "Problem-Solving",
    "Analytical Skills",
    "Leadership",
    "Management",
    "Organizational Skills",
    "Interpersonal Skills",
    "Negotiation",
    "Adaptability",
    "Emotional Intelligence",
    "Critical Thinking",
    "Active Listening",
    "Self-Motivation",
    "Sales",
    "Data Analysis",
    "Marketing",
    "Customer Relationship Management",
    "Python",
    "SQL",
    "Machine Learning",
    "Artificial Intelligence",
    "Blockchain",
    "Agile Methodology",
    "Cloud Computing",
    "Digital Marketing",
    "Project Management",
    "Business Analysis",
    "Change Management",
    "Social Media",
    "Customer Service",
    "Business Development",
    "Research Skills",
    "Prompt Engineering"
]

exprience_level = ['Internship', 'Entry level', 'Associate', 'Director',
                    'Mid-Senior level', 'Executive']

job_type = ['Full-time', 'Contract', 'Volunteer', 'Part-time', 
            'Temporary', 'Intership', 'Other']

remote = ['On-site', 'Hybrid', 'Remote']
